### PR TITLE
RSquared - Adjusted RSquared

### PR DESCRIPTION
**Pull request by magaras**
Moved **RSquared** as a method inside the class and created a method to calculate the **Adjusted RSquared**.

Both methods can be called like this:

`$object= new PolynomialRegression(2);`

`...`

`$rsquared = $object->RSquared($data, $coefficients);`

`$radjusted = $object->RAdjusted($rsquared, 1, count($data));`

I have also included a new test file (_RSquaredTest.php_) to verify the calculations.
References for the Adjusted RSquared can be found in the method's comments.

### CODE REVIEW

**Comment by magaras** [comment]
Hi John,
how are you? I hope everything is fine.

I was wondering if you are willing to accept my merge request or you have any objections.

Thank you very much!

**Comment by jbboehr** [comment]
@magaras It would be better if it was merged into [upstream](http://PolynomialRegression.drque.net/), but I think it's ok to merge it. Thanks!

**Comment by magaras** [comment]
Oh.. I thought that the versions were the same both here and in [upstream](http://polynomialregression.drque.net/).

Is the version [here ](http://polynomialregression.drque.net/) (_1.2.1 as i see_) maintained by you or do you have a repo for that also?

**Comment by jbboehr** [comment]
No, I just took it, added a namespace for PSR autoloader, added unit tests, and added it to packagist. It's not my library.

**Comment by jbboehr** [comment]
The composer.json should indicate this.

**Comment by magaras** [comment]
You are right.. I totally missed it.

**Pull request merged**
